### ISSUE TITLE
Error building iOS_arm64 on macOS 10.13.2

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#107]
output:
```
(venv) Chriss-MBP:kiwix-build chrisli$ ./kiwix-build.py kiwix-lib --target-platform iOS_arm64
WARNING: kiwix-build has not been tested on MacOS platfrom.
Tests, bug reports and patches are welcomed.
[INSTALL PACKAGES]
SKIP
[PREPARE]
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources zlib :
  download zlib : SKIP
  extract zlib : SKIP
  patch zlib : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
prepare sources icu4c :
  svncheckout icu4c_native : SKIP
  svnupdate icu4c_native : OK
  patch icu4c_native : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources kiwix-lib :
  gitclone kiwix-lib : SKIP
  gitupdate kiwix-lib : OK
[BUILD]
build pugixml :
  configure pugixml : ERROR
Traceback (most recent call last):
  File "./kiwix-build.py", line 1030, in <module>
    builder.run()
  File "./kiwix-build.py", line 964, in run
    self.build()
  File "./kiwix-build.py", line 948, in build
    builder.build()
  File "/Users/chrisli/Developer/kiwix-build/dependency_utils.py", line 224, in build
    self.command('configure', self._configure)
  File "/Users/chrisli/Developer/kiwix-build/dependency_utils.py", line 219, in command
    return self.target.command(*args, **kwargs)
  File "/Users/chrisli/Developer/kiwix-build/dependency_utils.py", line 50, in command
    ret = function(*args, context=context)
  File "/Users/chrisli/Developer/kiwix-build/dependency_utils.py", line 346, in _configure
    if not self.target.force_native_build and self.buildEnv.meson_crossfile:
  File "./kiwix-build.py", line 342, in __getattr__
    return getattr(self.options, name)
AttributeError: 'Namespace' object has no attribute 'meson_crossfile'
```

**Comment by kelson42** [comment]
@mgautierfr May you please handle that ticket in priority? @automactic needs to use all the nice new things you have built in the libkiwix :)

**Comment by automactic** [comment]
@mgautierfr Have you made any progress?

**Comment by mgautierfr** [comment]
I've just forced push a new version of ios branch.
You should be able to compile `kiwix-lib` for iOS.

However you will need to use meson 0.43.0, not meson 0.44.0. There is a bug (https://github.com/mesonbuild/meson/issues/2785) in the last version and the dependency detection will fail when compiling `kiwix-lib`

**Comment by automactic** [comment]
It failed...

I am using the iOS branch of this repo. 
```
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ ./kiwix-build.py --target-platform iOS_arm64
WARNING: kiwix-build has not been tested on MacOS platfrom.
Tests, bug reports and patches are welcomed.
[INSTALL PACKAGES]
 - autoconf : SKIP
 - automake : SKIP
 - libtool : SKIP
 - cmake : SKIP
 - pkg-config : SKIP
SKIP, No package to install.
[PREPARE]
prepare sources pugixml :
  download pugixml : OK1.50%
  extract pugixml : OK
  patch pugixml : OK
prepare sources zlib :
  download zlib : OK0.41%
  extract zlib : OK
  patch zlib : OK
prepare sources lzma :
  download lzma : OK0.02%
  extract lzma : OK
prepare sources xapian-core :
  download xapian-core : OK0.26%
  extract xapian-core : OK
prepare sources icu4c :
  svncheckout icu4c_native : OK
  svnupdate icu4c_native : OK
  patch icu4c_native : OK
prepare sources libzim :
  gitclone libzim : OK
  gitupdate libzim : OK
prepare sources kiwix-lib :
  gitclone kiwix-lib : OK
  gitupdate kiwix-lib : OK
prepare sources libmicrohttpd :
  download libmicrohttpd : OK0.31%
  extract libmicrohttpd : OK
prepare sources kiwix-tools :
  gitclone kiwix-tools : OK
  gitupdate kiwix-tools : OK
[BUILD]
build pugixml :
  configure pugixml : OK
  compile pugixml : OK
  test pugixml : OK
  install pugixml : OK
build zlib :
  pre_build_script zlib : OK
  configure zlib : OK
  compile zlib : OK
  install zlib : OK
build lzma :
  configure lzma : OK
  compile lzma : OK
  install lzma : OK
build xapian-core :
  configure xapian-core : OK
  compile xapian-core : OK
  install xapian-core : OK
build icu4c_native :
  configure icu4c_native : OK
  compile icu4c_native : OK
  install icu4c_native : SKIP
build icu4c_cross-compile :
  configure icu4c_cross-compile : OK
  compile icu4c_cross-compile : OK
  install icu4c_cross-compile : OK
build libzim :
  configure libzim : OK
  compile libzim : OK
  test libzim : OK
  install libzim : OK
build kiwix-lib :
  configure kiwix-lib : OK
  compile kiwix-lib : OK
  test kiwix-lib : OK
  install kiwix-lib : OK
build libmicrohttpd :
  configure libmicrohttpd : OK
  compile libmicrohttpd : OK
  install libmicrohttpd : OK
build kiwix-tools :
  configure kiwix-tools : OK
  compile kiwix-tools : ERROR
[1/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++ -Isrc/reader/kiwix-read@exe -Isrc/reader -I../../SOURCE/kiwix-tools/src/reader -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/ -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/reader/kiwix-read@exe/kiwix-read.cpp.o' -MF 'src/reader/kiwix-read@exe/kiwix-read.cpp.o.d' -o 'src/reader/kiwix-read@exe/kiwix-read.cpp.o' -c ../../SOURCE/kiwix-tools/src/reader/kiwix-read.cpp
../../SOURCE/kiwix-tools/src/reader/kiwix-read.cpp:85:18: warning: unused variable 'contentLength' [-Wunused-variable]
    unsigned int contentLength = 0;
                 ^
1 warning generated.
[2/13] /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/bin/kiwix-compile-resources --cxxfile static/server/server-resources.cpp --hfile static/server/server-resources.h ../../SOURCE/kiwix-tools/static/server/resources_list.txt
jquery-ui/jquery-ui.structure.min.css ['jquery_ui', 'jquery_ui_structure_min_css']
jquery-ui/jquery-ui.min.js ['jquery_ui', 'jquery_ui_min_js']
jquery-ui/external/jquery/jquery.js ['jquery_ui', 'external', 'jquery', 'jquery_js']
jquery-ui/images/ui-bg_flat_0_aaaaaa_40x100.png ['jquery_ui', 'images', 'ui_bg_flat_0_aaaaaa_40x100_png']
jquery-ui/images/ui-bg_flat_75_ffffff_40x100.png ['jquery_ui', 'images', 'ui_bg_flat_75_ffffff_40x100_png']
jquery-ui/images/ui-icons_222222_256x240.png ['jquery_ui', 'images', 'ui_icons_222222_256x240_png']
jquery-ui/images/ui-bg_glass_55_fbf9ee_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_55_fbf9ee_1x400_png']
jquery-ui/images/ui-bg_highlight-soft_75_cccccc_1x100.png ['jquery_ui', 'images', 'ui_bg_highlight_soft_75_cccccc_1x100_png']
jquery-ui/images/ui-bg_glass_65_ffffff_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_65_ffffff_1x400_png']
jquery-ui/images/ui-icons_2e83ff_256x240.png ['jquery_ui', 'images', 'ui_icons_2e83ff_256x240_png']
jquery-ui/images/ui-icons_cd0a0a_256x240.png ['jquery_ui', 'images', 'ui_icons_cd0a0a_256x240_png']
jquery-ui/images/ui-icons_888888_256x240.png ['jquery_ui', 'images', 'ui_icons_888888_256x240_png']
jquery-ui/images/ui-bg_glass_75_e6e6e6_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_75_e6e6e6_1x400_png']
jquery-ui/images/animated-overlay.gif ['jquery_ui', 'images', 'animated_overlay_gif']
jquery-ui/images/ui-bg_glass_75_dadada_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_75_dadada_1x400_png']
jquery-ui/images/ui-icons_454545_256x240.png ['jquery_ui', 'images', 'ui_icons_454545_256x240_png']
jquery-ui/images/ui-bg_glass_95_fef1ec_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_95_fef1ec_1x400_png']
jquery-ui/jquery-ui.theme.min.css ['jquery_ui', 'jquery_ui_theme_min_css']
jquery-ui/jquery-ui.min.css ['jquery_ui', 'jquery_ui_min_css']
home.html.tmpl ['home_html_tmpl']
include.html.part ['include_html_part']
taskbar.css ['taskbar_css']
taskbar.html.part ['taskbar_html_part']
global_taskbar.html.part ['global_taskbar_html_part']
[3/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++ -Isrc/searcher/kiwix-search@exe -Isrc/searcher -I../../SOURCE/kiwix-tools/src/searcher -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/ -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/searcher/kiwix-search@exe/kiwix-search.cpp.o' -MF 'src/searcher/kiwix-search@exe/kiwix-search.cpp.o.d' -o 'src/searcher/kiwix-search@exe/kiwix-search.cpp.o' -c ../../SOURCE/kiwix-tools/src/searcher/kiwix-search.cpp
[4/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -o src/reader/kiwix-read 'src/reader/kiwix-read@exe/kiwix-read.cpp.o' -static-libstdc++ --static -pthread -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib64 -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lkiwix -lzim -llzma -D_THREAD_SAFE -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -lxapian -lz -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lmicrohttpd -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lz -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++
FAILED: src/reader/kiwix-read
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -o src/reader/kiwix-read 'src/reader/kiwix-read@exe/kiwix-read.cpp.o' -static-libstdc++ --static -pthread -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib64 -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lkiwix -lzim -llzma -D_THREAD_SAFE -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -lxapian -lz -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lmicrohttpd -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lz -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
ld: warning: directory not found for option '-L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib64'
ld: unknown option: --static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[5/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -o src/searcher/kiwix-search 'src/searcher/kiwix-search@exe/kiwix-search.cpp.o' -static-libstdc++ --static -pthread -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib64 -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lkiwix -lzim -llzma -D_THREAD_SAFE -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -lxapian -lz -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lmicrohttpd -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lz -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++
FAILED: src/searcher/kiwix-search
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  -o src/searcher/kiwix-search 'src/searcher/kiwix-search@exe/kiwix-search.cpp.o' -static-libstdc++ --static -pthread -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib64 -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lkiwix -lzim -llzma -D_THREAD_SAFE -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -lxapian -lz -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lmicrohttpd -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -lz -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++
clang: warning: argument unused during compilation: '-static-libstdc++' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
ld: warning: directory not found for option '-L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib64'
ld: unknown option: --static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[6/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++ -Isrc/installer/kiwix-install@exe -Isrc/installer -I../../SOURCE/kiwix-tools/src/installer -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/ -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/installer/kiwix-install@exe/kiwix-install.cpp.o' -MF 'src/installer/kiwix-install@exe/kiwix-install.cpp.o.d' -o 'src/installer/kiwix-install@exe/kiwix-install.cpp.o' -c ../../SOURCE/kiwix-tools/src/installer/kiwix-install.cpp
[7/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++ -Isrc/manager/kiwix-manage@exe -Isrc/manager -I../../SOURCE/kiwix-tools/src/manager -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/ -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/manager/kiwix-manage@exe/kiwix-manage.cpp.o' -MF 'src/manager/kiwix-manage@exe/kiwix-manage.cpp.o.d' -o 'src/manager/kiwix-manage@exe/kiwix-manage.cpp.o' -c ../../SOURCE/kiwix-tools/src/manager/kiwix-manage.cpp
[8/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++ -Isrc/server/kiwix-serve@exe -Isrc/server -I../../SOURCE/kiwix-tools/src/server -Istatic/server -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/ -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/server/kiwix-serve@exe/request_context.cpp.o' -MF 'src/server/kiwix-serve@exe/request_context.cpp.o.d' -o 'src/server/kiwix-serve@exe/request_context.cpp.o' -c ../../SOURCE/kiwix-tools/src/server/request_context.cpp
[9/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++ -Isrc/server/kiwix-serve@exe -Isrc/server -I../../SOURCE/kiwix-tools/src/server -Istatic/server -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/ -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' -MF 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o.d' -o 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' -c ../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp
FAILED: src/server/kiwix-serve@exe/kiwix-serve.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++ -Isrc/server/kiwix-serve@exe -Isrc/server -I../../SOURCE/kiwix-tools/src/server -Istatic/server -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/ -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' -MF 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o.d' -o 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' -c ../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp
../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:111:11: warning: comparison of constant 18446744073709551615 with expression of type 'unsigned int' is always true [-Wtautological-constant-out-of-range-compare]
  if (pos != std::string::npos) {
      ~~~ ^  ~~~~~~~~~~~~~~~~~
../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:221:35: warning: 'MHD_create_response_from_data' is deprecated: MHD_create_response_from_data() is deprecated, use MHD_create_response_from_buffer() [-Wdeprecated-declarations]
  struct MHD_Response* response = MHD_create_response_from_data(
                                  ^
/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/microhttpd.h:2032:1: note: 'MHD_create_response_from_data' has been explicitly marked deprecated here
_MHD_DEPR_FUNC("MHD_create_response_from_data() is deprecated, use MHD_create_response_from_buffer()") \
^
/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/microhttpd.h:244:44: note: expanded from macro '_MHD_DEPR_FUNC'
#define _MHD_DEPR_FUNC(msg) __attribute__((deprecated(msg)))
                                           ^
../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:547:27: error: no member named 'getHtml' in 'kiwix::Searcher'
      content = searcher->getHtml();
                ~~~~~~~~  ^
2 warnings and 1 error generated.
[10/13] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 -stdlib=libc++ -Isrc/server/kiwix-serve@exe -Isrc/server -I../../SOURCE/kiwix-tools/src/server -Istatic/server -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include/ -I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include -Xclang -fcolor-diagnostics -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/server/kiwix-serve@exe/meson-generated_.._.._.._static_server_server-resources.cpp.o' -MF 'src/server/kiwix-serve@exe/meson-generated_.._.._.._static_server_server-resources.cpp.o.d' -o 'src/server/kiwix-serve@exe/meson-generated_.._.._.._static_server_server-resources.cpp.o' -c static/server/server-resources.cpp
ninja: build stopped: subcommand failed.
run command 'ninja -v'
current directory is '/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-tools'
env is :
  TERM_PROGRAM : 'iTerm.app'
  TERM : 'xterm-256color'
  SHELL : '/bin/bash'
  TMPDIR : '/var/folders/w0/ph55y7r54tld0qb0kyybvbs40000gn/T/'
  Apple_PubSub_Socket_Render : '/private/tmp/com.apple.launchd.ZAezo9Eu60/Render'
  TERM_PROGRAM_VERSION : '3.1.5'
  OLDPWD : '/Users/chrisli/Developer/kiwix-build/ninja'
  TERM_SESSION_ID : 'w0t0p0:AD4D863B-DCC2-4A59-A080-0A8F839CDAC4'
  USER : 'chrisli'
  SSH_AUTH_SOCK : '/private/tmp/com.apple.launchd.5AVTaxGbbL/Listeners'
  __CF_USER_TEXT_ENCODING : '0x1F5:0x0:0x0'
  VIRTUAL_ENV : '/Users/chrisli/Developer/kiwix-build/venv'
  PATH : '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk/bin:/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/bin:/Users/chrisli/Developer/kiwix-build/venv/bin:/Users/chrisli/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
  PWD : '/Users/chrisli/Developer/kiwix-build'
  LANG : 'en_US.UTF-8'
  ITERM_PROFILE : 'Default'
  XPC_FLAGS : '0x0'
  PS1 : '(venv) \\h:\\W \\u\\$ '
  XPC_SERVICE_NAME : '0'
  SHLVL : '1'
  HOME : '/Users/chrisli'
  COLORFGBG : '0;15'
  ITERM_SESSION_ID : 'w0t0p0:AD4D863B-DCC2-4A59-A080-0A8F839CDAC4'
  LOGNAME : 'chrisli'
  COLORTERM : 'truecolor'
  _ : './kiwix-build.py'
  CFLAGS : ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0 '
  CXXFLAGS : ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk -arch arm64 -miphoneos-version-min=9.0  -stdlib=libc++ -std=c++11 '
  LDFLAGS : '-L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk '
  MACOSX_DEPLOYMENT_TARGET : '10.4'
  CC : '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang'
  CXX : '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++'
  PKG_CONFIG_PATH : ':/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib/pkgconfig'
  LD_LIBRARY_PATH : ':/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib:/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib'
  CPPFLAGS : '-I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include '

Stopping build due to errors
```

**Comment by mgautierfr** [comment]
`kiwix-tools` is not `kiwix-lib` :)

`kiwix-tools` doesn't compile on macOS (nor iOS) because `kiwix-serve` depends of `ctpp2` to render the search result html. And `ctpp2` doesn't compile on macOS (at least the last time we've tried) .

**Comment by kelson42** [comment]
@mgautierfr What command should exactly run @automactic ?

**Comment by mgautierfr** [comment]
The same of its first comment :
`./kiwix-build.py kiwix-lib --target-platform iOS_arm64`

**Comment by automactic** [comment]
Ah, yes it compiles. Also seems to work on real devices. Yay!
