### ISSUE TITLE
cross build on macOS targeting iOS_arm64 failed

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#165]
```
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ python -m kiwixbuild kiwix-lib --target-platform iOS_arm64
WARNING: kiwix-build has not been tested on MacOS platfrom.
Tests, bug reports and patches are welcomed.
[INSTALL PACKAGES]
 - autoconf : SKIP
 - automake : SKIP
 - libtool : SKIP
 - cmake : SKIP
 - pkg-config : SKIP
SKIP, No package to install.
[PREPARE]
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources zlib :
  download zlib : SKIP
  extract zlib : SKIP
  patch zlib : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
prepare sources icu4c :
  svncheckout icu4c_native : SKIP
  svnupdate icu4c_native : SKIP
  patch icu4c_native : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources libaria2 :
  download libaria2 : SKIP
  extract libaria2 : SKIP
  patch libaria2 : SKIP
  post_prepare_script libaria2 : SKIP
prepare sources kiwix-lib :
  gitclone kiwix-lib : SKIP
  gitupdate kiwix-lib : OK
[BUILD]
build pugixml :
  configure pugixml : OK
  compile pugixml : OK
  test pugixml : OK
  install pugixml : OK
build zlib :
  pre_build_script zlib : OK
  configure zlib : OK
  compile zlib : OK
  install zlib : OK
build lzma :
  configure lzma : OK
  compile lzma : OK
  install lzma : OK
build xapian-core :
  configure xapian-core : OK
  compile xapian-core : OK
  install xapian-core : OK
build icu4c_native :
  configure icu4c_native : OK
  compile icu4c_native : OK
  install icu4c_native : SKIP
build icu4c_cross-compile :
  configure icu4c_cross-compile : OK
  compile icu4c_cross-compile : OK
  install icu4c_cross-compile : OK
build libzim :
  configure libzim : OK
  compile libzim : OK
  test libzim : OK
  install libzim : OK
build libaria2 :
  configure libaria2 : OK
  compile libaria2 : OK
  install libaria2 : OK
build kiwix-lib :
  configure kiwix-lib : ERROR
The Meson build system
Version: 0.44.0
Source dir: /Users/chrisli/Developer/kiwix-build/SOURCE/kiwix-lib
Build dir: /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib
Build type: cross build
Project name: kiwix-lib
Native C++ compiler: c++ (clang 9.1.0)
Appending CXXFLAGS from environment: ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -arch arm64 -miphoneos-version-min=9.0  -stdlib=libc++ -std=c++11 '
Appending LDFLAGS from environment: '-L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk '
Appending CPPFLAGS from environment: '-I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include '
Cross C++ compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ (clang 9.1.0)
Host machine cpu family: arm64
Host machine cpu: arm64
Target machine cpu family: arm64
Target machine cpu: arm64
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Dependency icu-i18n found: NO

Meson encountered an error in file meson.build, line 12, column 0:
Dependency 'icu-i18n' not found, tried Extra Frameworks and Pkg-Config:

Static library not found for 'pthread'

A full log can be found at /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib/meson-logs/meson-log.txt
run command 'meson . /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib --default-library=static -Dctpp2-install-prefix=/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL --prefix=/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL --libdir=lib --cross-file /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/meson_cross_file.txt'
current directory is '/Users/chrisli/Developer/kiwix-build/SOURCE/kiwix-lib'
env is :
  TERM_PROGRAM : 'iTerm.app'
  TERM : 'xterm-256color'
  SHELL : '/bin/bash'
  TMPDIR : '/var/folders/w0/ph55y7r54tld0qb0kyybvbs40000gn/T/'
  Apple_PubSub_Socket_Render : '/private/tmp/com.apple.launchd.PAhTiDQqrj/Render'
  TERM_PROGRAM_VERSION : '3.1.5'
  OLDPWD : '/Users/chrisli/Developer/kiwix-build/ninja'
  TERM_SESSION_ID : 'w0t1p0:FAA2FCEB-22E9-4B57-AE6F-091F18410589'
  USER : 'chrisli'
  SSH_AUTH_SOCK : '/private/tmp/com.apple.launchd.hV7rzPlxcu/Listeners'
  __CF_USER_TEXT_ENCODING : '0x1F5:0x0:0x0'
  VIRTUAL_ENV : '/Users/chrisli/Developer/kiwix-build/venv'
  PATH : '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/bin:/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/bin:/Users/chrisli/Developer/kiwix-build/venv/bin:/usr/local/opt/php/bin:/Users/chrisli/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gettext/bin'
  PWD : '/Users/chrisli/Developer/kiwix-build'
  LANG : 'en_US.UTF-8'
  ITERM_PROFILE : 'Default'
  XPC_FLAGS : '0x0'
  PS1 : '(venv) \\h:\\W \\u\\$ '
  XPC_SERVICE_NAME : '0'
  SHLVL : '1'
  HOME : '/Users/chrisli'
  COLORFGBG : '0;15'
  ITERM_SESSION_ID : 'w0t1p0:FAA2FCEB-22E9-4B57-AE6F-091F18410589'
  LOGNAME : 'chrisli'
  COLORTERM : 'truecolor'
  _ : '/Users/chrisli/Developer/kiwix-build/venv/bin/python'
  CFLAGS : ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -arch arm64 -miphoneos-version-min=9.0 '
  CXXFLAGS : ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -arch arm64 -miphoneos-version-min=9.0  -stdlib=libc++ -std=c++11 '
  LDFLAGS : '-L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk '
  MACOSX_DEPLOYMENT_TARGET : '10.7'
  PKG_CONFIG_PATH : ':/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib/pkgconfig'
  LD_LIBRARY_PATH : ':/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib:/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib'
  CPPFLAGS : '-I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include '

Stopping build due to errors
```

**Comment by mgautierfr** [comment]
This works on my mac.
@automactic , can you make an archive of your `BUILD_iOS_arm64` directory and publish it somewhere ?

**Comment by automactic** [comment]
@mgautierfr https://www.dropbox.com/s/lsonemo9i44ad0z/BUILD_iOS_arm64.zip

**Comment by mgautierfr** [comment]
It may be due to this issue https://github.com/mesonbuild/meson/issues/2785.
Can you update meson to another version than 0.44.0 (higher or 0.43.0) ?

**Comment by automactic** [comment]
lemme try

**Comment by automactic** [comment]
was using meson -0.44.0, now using meson-0.46.0
ninja version: 1.8.2

New error:
```
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ python -m kiwixbuild kiwix-lib --target-platform iOS_arm64
WARNING: kiwix-build has not been tested on MacOS platfrom.
Tests, bug reports and patches are welcomed.
[INSTALL PACKAGES]
 - autoconf : SKIP
 - automake : SKIP
 - libtool : SKIP
 - cmake : SKIP
 - pkg-config : SKIP
SKIP, No package to install.
[PREPARE]
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources zlib :
  download zlib : SKIP
  extract zlib : SKIP
  patch zlib : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
prepare sources icu4c :
  svncheckout icu4c_native : SKIP
  svnupdate icu4c_native : SKIP
  patch icu4c_native : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources libaria2 :
  download libaria2 : SKIP
  extract libaria2 : SKIP
  patch libaria2 : SKIP
  post_prepare_script libaria2 : SKIP
prepare sources kiwix-lib :
  gitclone kiwix-lib : SKIP
  gitupdate kiwix-lib : OK
[BUILD]
build pugixml :
  configure pugixml : OK
  compile pugixml : OK
  test pugixml : OK
  install pugixml : OK
build zlib :
  pre_build_script zlib : OK
  configure zlib : OK
  compile zlib : OK
  install zlib : OK
build lzma :
  configure lzma : OK
  compile lzma : OK
  install lzma : OK
build xapian-core :
  configure xapian-core : OK
  compile xapian-core : OK
  install xapian-core : OK
build icu4c_native :
  configure icu4c_native : OK
  compile icu4c_native : OK
  install icu4c_native : SKIP
build icu4c_cross-compile :
  configure icu4c_cross-compile : OK
  compile icu4c_cross-compile : OK
  install icu4c_cross-compile : OK
build libzim :
  configure libzim : OK
  compile libzim : OK
  test libzim : OK
  install libzim : OK
build libaria2 :
  configure libaria2 : OK
  compile libaria2 : OK
  install libaria2 : OK
build kiwix-lib :
  configure kiwix-lib : ERROR
The Meson build system
Version: 0.44.0
Source dir: /Users/chrisli/Developer/kiwix-build/SOURCE/kiwix-lib
Build dir: /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib
Build type: cross build
Project name: kiwix-lib
Native C++ compiler: c++ (clang 9.1.0)
Appending CXXFLAGS from environment: ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -arch arm64 -miphoneos-version-min=9.0  -stdlib=libc++ -std=c++11 '
Appending LDFLAGS from environment: '-L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk '
Appending CPPFLAGS from environment: '-I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include '
Cross C++ compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ (clang 9.1.0)
Host machine cpu family: arm64
Host machine cpu: arm64
Target machine cpu family: arm64
Target machine cpu: arm64
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Dependency icu-i18n found: NO

Meson encountered an error in file meson.build, line 12, column 0:
Dependency 'icu-i18n' not found, tried Extra Frameworks and Pkg-Config:

Static library not found for 'pthread'

A full log can be found at /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib/meson-logs/meson-log.txt
run command 'meson . /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib --default-library=static -Dctpp2-install-prefix=/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL --prefix=/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL --libdir=lib --cross-file /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/meson_cross_file.txt'
current directory is '/Users/chrisli/Developer/kiwix-build/SOURCE/kiwix-lib'
env is :
  TERM_PROGRAM : 'iTerm.app'
  TERM : 'xterm-256color'
  SHELL : '/bin/bash'
  TMPDIR : '/var/folders/w0/ph55y7r54tld0qb0kyybvbs40000gn/T/'
  Apple_PubSub_Socket_Render : '/private/tmp/com.apple.launchd.PAhTiDQqrj/Render'
  TERM_PROGRAM_VERSION : '3.1.5'
  OLDPWD : '/Users/chrisli/Developer/kiwix-build/ninja'
  TERM_SESSION_ID : 'w0t1p0:FAA2FCEB-22E9-4B57-AE6F-091F18410589'
  USER : 'chrisli'
  SSH_AUTH_SOCK : '/private/tmp/com.apple.launchd.hV7rzPlxcu/Listeners'
  __CF_USER_TEXT_ENCODING : '0x1F5:0x0:0x0'
  VIRTUAL_ENV : '/Users/chrisli/Developer/kiwix-build/venv'
  PATH : '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/bin:/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/bin:/Users/chrisli/Developer/kiwix-build/venv/bin:/usr/local/opt/php/bin:/Users/chrisli/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gettext/bin'
  PWD : '/Users/chrisli/Developer/kiwix-build'
  LANG : 'en_US.UTF-8'
  ITERM_PROFILE : 'Default'
  XPC_FLAGS : '0x0'
  PS1 : '(venv) \\h:\\W \\u\\$ '
  XPC_SERVICE_NAME : '0'
  SHLVL : '1'
  HOME : '/Users/chrisli'
  COLORFGBG : '0;15'
  ITERM_SESSION_ID : 'w0t1p0:FAA2FCEB-22E9-4B57-AE6F-091F18410589'
  LOGNAME : 'chrisli'
  COLORTERM : 'truecolor'
  _ : '/Users/chrisli/Developer/kiwix-build/venv/bin/python'
  CFLAGS : ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -arch arm64 -miphoneos-version-min=9.0 '
  CXXFLAGS : ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -arch arm64 -miphoneos-version-min=9.0  -stdlib=libc++ -std=c++11 '
  LDFLAGS : '-L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk '
  MACOSX_DEPLOYMENT_TARGET : '10.7'
  PKG_CONFIG_PATH : ':/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib/pkgconfig'
  LD_LIBRARY_PATH : ':/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib:/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib'
  CPPFLAGS : '-I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include '

Stopping build due to errors
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ meson
/Library/Frameworks/Python.framework/Versions/3.6/bin/meson <source directory> <build directory>
If you omit either directory, the current directory is substituted.
Run /Library/Frameworks/Python.framework/Versions/3.6/bin/meson --help for more information.
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ which meson
/Library/Frameworks/Python.framework/Versions/3.6/bin/meson
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ meson --version
0.44.0
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ pip install meson
Collecting meson
  Downloading https://files.pythonhosted.org/packages/17/d0/0fe98a9557a2f07dbe6f99ef57f2bc37450b641e1f6ceae9ce04c3c845dd/meson-0.46.0.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 2.9MB/s
Building wheels for collected packages: meson
  Running setup.py bdist_wheel for meson ... done
  Stored in directory: /Users/chrisli/Library/Caches/pip/wheels/a3/90/e2/acb1ec5736d690af2d5c5eb337cdd9d454143c68e0bb685961
Successfully built meson
Installing collected packages: meson
Successfully installed meson-0.46.0
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ which meson
/Users/chrisli/Developer/kiwix-build/venv/bin/meson
(venv) Chriss-MacBook-Pro:kiwix-build chrisli$ python -m kiwixbuild kiwix-lib --target-platform iOS_arm64
WARNING: kiwix-build has not been tested on MacOS platfrom.
Tests, bug reports and patches are welcomed.
[INSTALL PACKAGES]
SKIP
[PREPARE]
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources zlib :
  download zlib : SKIP
  extract zlib : SKIP
  patch zlib : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
prepare sources icu4c :
  svncheckout icu4c_native : SKIP
  svnupdate icu4c_native : SKIP
  patch icu4c_native : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources libaria2 :
  download libaria2 : SKIP
  extract libaria2 : SKIP
  patch libaria2 : SKIP
  post_prepare_script libaria2 : SKIP
prepare sources kiwix-lib :
  gitclone kiwix-lib : SKIP
  gitupdate kiwix-lib : OK
[BUILD]
build pugixml :
  configure pugixml : SKIP
  compile pugixml : OK
  test pugixml : OK
  install pugixml : OK
build zlib :
  pre_build_script zlib : SKIP
  configure zlib : SKIP
  compile zlib : SKIP
  install zlib : SKIP
build lzma :
  configure lzma : SKIP
  compile lzma : SKIP
  install lzma : SKIP
build xapian-core :
  configure xapian-core : SKIP
  compile xapian-core : SKIP
  install xapian-core : SKIP
build icu4c_native :
  configure icu4c_native : SKIP
  compile icu4c_native : SKIP
  install icu4c_native : SKIP
build icu4c_cross-compile :
  configure icu4c_cross-compile : SKIP
  compile icu4c_cross-compile : SKIP
  install icu4c_cross-compile : SKIP
build libzim :
  configure libzim : SKIP
  compile libzim : OK
  test libzim : OK
  install libzim : OK
build libaria2 :
  configure libaria2 : SKIP
  compile libaria2 : SKIP
  install libaria2 : SKIP
build kiwix-lib :
  configure kiwix-lib : OK
  compile kiwix-lib : OK
  test kiwix-lib : OK
  install kiwix-lib : ERROR
[0/1] /Users/chrisli/Developer/kiwix-build/venv/bin/python3.6 /Users/chrisli/Developer/kiwix-build/venv/bin/meson --internal install /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib/meson-private/install.dat
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: input file: /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib/libkiwix.a is not a Mach-O file
Installing src/libkiwix.a to /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib/libkiwix.a
Traceback (most recent call last):
  File "/Users/chrisli/Developer/kiwix-build/venv/bin/meson", line 26, in <module>
    sys.exit(main())
  File "/Users/chrisli/Developer/kiwix-build/venv/bin/meson", line 23, in main
    return mesonmain.run(sys.argv[1:], launcher)
  File "/Users/chrisli/Developer/kiwix-build/venv/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 308, in run
    sys.exit(run_script_command(args[1:]))
  File "/Users/chrisli/Developer/kiwix-build/venv/lib/python3.6/site-packages/mesonbuild/mesonmain.py", line 257, in run_script_command
    return cmdfunc(cmdargs)
  File "/Users/chrisli/Developer/kiwix-build/venv/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 390, in run
    do_install(datafilename)
  File "/Users/chrisli/Developer/kiwix-build/venv/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 216, in do_install
    install_targets(d)
  File "/Users/chrisli/Developer/kiwix-build/venv/lib/python3.6/site-packages/mesonbuild/scripts/meson_install.py", line 371, in install_targets
    depfixer.fix_rpath(outname, install_rpath, False)
  File "/Users/chrisli/Developer/kiwix-build/venv/lib/python3.6/site-packages/mesonbuild/scripts/depfixer.py", line 391, in fix_rpath
    fix_darwin(fname, new_rpath)
  File "/Users/chrisli/Developer/kiwix-build/venv/lib/python3.6/site-packages/mesonbuild/scripts/depfixer.py", line 376, in fix_darwin
    subprocess.check_call(['install_name_tool', '-add_rpath', new_rpath, fname])
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['install_name_tool', '-add_rpath', '$ORIGIN', '/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib/libkiwix.a']' returned non-zero exit status 1.
FAILED: meson-install
/Users/chrisli/Developer/kiwix-build/venv/bin/python3.6 /Users/chrisli/Developer/kiwix-build/venv/bin/meson --internal install /Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib/meson-private/install.dat
ninja: build stopped: subcommand failed.
run command 'ninja -v install'
current directory is '/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/kiwix-lib'
env is :
  TERM_PROGRAM : 'iTerm.app'
  TERM : 'xterm-256color'
  SHELL : '/bin/bash'
  TMPDIR : '/var/folders/w0/ph55y7r54tld0qb0kyybvbs40000gn/T/'
  Apple_PubSub_Socket_Render : '/private/tmp/com.apple.launchd.PAhTiDQqrj/Render'
  TERM_PROGRAM_VERSION : '3.1.5'
  OLDPWD : '/Users/chrisli/Developer/kiwix-build/ninja'
  TERM_SESSION_ID : 'w0t1p0:FAA2FCEB-22E9-4B57-AE6F-091F18410589'
  USER : 'chrisli'
  SSH_AUTH_SOCK : '/private/tmp/com.apple.launchd.hV7rzPlxcu/Listeners'
  __CF_USER_TEXT_ENCODING : '0x1F5:0x0:0x0'
  VIRTUAL_ENV : '/Users/chrisli/Developer/kiwix-build/venv'
  PATH : '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk/bin:/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/bin:/Users/chrisli/Developer/kiwix-build/venv/bin:/usr/local/opt/php/bin:/Users/chrisli/.cargo/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/gettext/bin'
  PWD : '/Users/chrisli/Developer/kiwix-build'
  LANG : 'en_US.UTF-8'
  ITERM_PROFILE : 'Default'
  XPC_FLAGS : '0x0'
  PS1 : '(venv) \\h:\\W \\u\\$ '
  XPC_SERVICE_NAME : '0'
  SHLVL : '1'
  HOME : '/Users/chrisli'
  COLORFGBG : '0;15'
  ITERM_SESSION_ID : 'w0t1p0:FAA2FCEB-22E9-4B57-AE6F-091F18410589'
  LOGNAME : 'chrisli'
  COLORTERM : 'truecolor'
  _ : '/Users/chrisli/Developer/kiwix-build/venv/bin/python'
  CFLAGS : ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -arch arm64 -miphoneos-version-min=9.0 '
  CXXFLAGS : ' -fembed-bitcode -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -arch arm64 -miphoneos-version-min=9.0  -stdlib=libc++ -std=c++11 '
  LDFLAGS : '-L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib -L/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib  -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk '
  MACOSX_DEPLOYMENT_TARGET : '10.7'
  CC : '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang'
  CXX : '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++'
  PKG_CONFIG_PATH : ':/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib/pkgconfig'
  LD_LIBRARY_PATH : ':/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib:/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/lib'
  CPPFLAGS : '-I/Users/chrisli/Developer/kiwix-build/BUILD_iOS_arm64/INSTALL/include '

Stopping build due to errors
```

**Comment by mgautierfr** [comment]
@automactic,
Can you make a new archive of your BUILD_iOS_arm64 directory and publish it somewhere ?
I don't know why `install_name_tool` failed.

**Comment by automactic** [comment]
Here it is: https://www.dropbox.com/s/lsonemo9i44ad0z/BUILD_iOS_arm64.zip?dl=0

**Comment by kelson42** [comment]
@mgautierfr Can you please with high prio handle that question/problem? Kiwix iOS has been delayed for months and we really need to release now.

**Comment by automactic** [comment]
Yes I added `-fembed-bitcode`, it allows apple to recompile the app on their side and reduce app size / download size, make things faster, etc.

I would say if this problem is impossible to solve now, it is ok to remove it. But eventually we need to (and should) use this flag.

**Comment by automactic** [comment]
@mgautierfr Why are we building dylibs not static ones now?

**Comment by automactic** [comment]
@mgautierfr, dylibs with iOS app does not seems to work. As my upload keeping being rejected by apple store. Could we build everything statics?

**Comment by kelson42** [comment]
Reading https://github.com/mesonbuild/meson/commit/7eb187c5f2cf55c6d441db08a87bac02cb58a9dc and https://github.com/mesonbuild/meson/issues/1037. Wonder if using ```b_asneeded=false``` would help

**Comment by kelson42** [comment]
@automactic Does that work now with master?

**Comment by automactic** [comment]
Master should work with meson 0.43.0. But please merge #166.

**Comment by nirbheek** [comment]
I have created a PR that should fix this: https://github.com/mesonbuild/meson/pull/3609/

Could you please try with that PR (and that build option) and tell me if the resulting iOS binaries look correct? Thanks!

**Comment by nirbheek** [comment]
@automactic did you set the option `-Db_bitcode` instead of setting the bitcode flags in CFLAGS?

**Comment by automactic** [comment]
@nirbheek, sorry I am not the author of this repo. Maybe @mgautierfr, can give you the answer.

**Comment by kelson42** [comment]
@mgautierfr What the status here? Could we benefit of @nirbheek patch?
@automactic Would you not be able to test with @nirbheek's branch/patch?

**Comment by nirbheek** [comment]
The bitcode patch has been merged in upstream Meson and the release is in 2 weeks. It seems to work well for gstreamer. The way to enable bitcode support is to call meson like so:

```
$ meson -Db_bitcode=true [...]
```

Do ***not*** set any bitcode flags in `CFLAGS`, `LDFLAGS`, etc.

It will print a one-time warning about [the consequences of passing that](https://github.com/mesonbuild/meson/blob/master/docs/markdown/Builtin-options.md#notes-about-apple-bitcode-support), and then enable that option wherever it can.

If you have any issues with this, please report it here or [upstream](https://github.com/mesonbuild/meson/issues/new).

**Comment by kelson42** [comment]
@automactic @mgautierfr What is the status on this old issue?

**Comment by mgautierfr** [comment]
I recently switch the CI to python3.5 and last meson. In the same time, I set the correct option `-Db_bitcode` for libzim and kiwix-lib. (See #213, b2d2e48)

@automactic Can you confirm this is correct on you side ?

**Comment by automactic** [comment]
Works! Tested on macOS 10.14.3, python 3.7. While I did not link the libs along with the app, I will reopen the issue if it doesn't work.
