### ISSUE TITLE
Crash by trying to build custom app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#67]
```
$ ./kiwix-build.py --target-platform android_arm --android-custom-app wikimed --zim-file-size $ZIM_SIZE kiwix-android-custom
[INSTALL PACKAGES]
 - automake : SKIP
 - cmake : SKIP
 - git : SKIP
 - subversion : SKIP
 - ccache : SKIP
 - pkg-config : SKIP
 - gcc : SKIP
 - default-jdk : SKIP
SKIP, No package to install.
[PREPARE]
prepare sources for toolchain android-ndk :
  download android-ndk : SKIP
  extract android-ndk : SKIP
prepare sources for toolchain android-sdk :
  download android-sdk : SKIP
  extract android-sdk : SKIP
prepare sources Gradle :
  download Gradle : SKIP
  extract Gradle : SKIP
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources zlib :
  download zlib : SKIP
  extract zlib : SKIP
  patch zlib : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources uuid :
  download uuid : SKIP
  extract uuid : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
  patch xapian-core : SKIP
prepare sources icu4c :
  svncheckout icu4c_native : SKIP
  svnupdate icu4c_native : OK
  patch icu4c_native : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources kiwix-lib :
  gitclone kiwix-lib : SKIP
  gitupdate kiwix-lib : OK
prepare sources kiwix-android :
  gitclone kiwix-android : SKIP
  gitupdate kiwix-android : OK
prepare sources kiwix-android-custom :
  gitclone kiwix-android-custom : SKIP
  gitupdate kiwix-android-custom : OK
[BUILD]
build toolchain android-ndk :
  build_platform android-ndk : OK
  fix_permission_right android-ndk : OK
build toolchain android-sdk :
  build_platform android-sdk : SKIP
  fix_licenses android-sdk : SKIP
build Gradle :
  install Gradle : OK
build pugixml :
  configure pugixml : OK
  compile pugixml : OK
  install pugixml : OK
build zlib :
  pre_build_script zlib : OK
  configure zlib : OK
  compile zlib : OK
  install zlib : OK
build lzma :
  configure lzma : OK
  compile lzma : OK
  install lzma : OK
build uuid :
  configure uuid : OK
  compile uuid : OK
  install uuid : OK
build xapian-core :
  configure xapian-core : OK
  compile xapian-core : OK
  install xapian-core : OK
build icu4c_native :
  configure icu4c_native : OK
  compile icu4c_native : OK
  install icu4c_native : SKIP
build icu4c_cross-compile :
  configure icu4c_cross-compile : OK
  compile icu4c_cross-compile : OK
  install icu4c_cross-compile : OK
build libzim :
  configure libzim : OK
  compile libzim : OK
  install libzim : OK
build kiwix-lib :
  configure kiwix-lib : OK
  compile kiwix-lib : OK
  install kiwix-lib : OK
build kiwix-android :
SKIP
build kiwix-android-custom :
  configure kiwix-android-custom : ERROR
Traceback (most recent call last):
  File "./kiwix-build.py", line 947, in <module>
    builder.run()
  File "./kiwix-build.py", line 885, in run
    self.build()
  File "./kiwix-build.py", line 875, in build
    builder.build()
  File "/home/kelson/kiwix-build/dependencies.py", line 412, in build
    self.command('configure', self._configure)
  File "/home/kelson/kiwix-build/dependency_utils.py", line 206, in command
    return self.target.command(*args, **kwargs)
  File "/home/kelson/kiwix-build/dependency_utils.py", line 50, in command
    ret = function(*args, context=context)
  File "/home/kelson/kiwix-build/dependencies.py", line 441, in _configure
    shutil.copytree(pj(self.buildEnv.install_dir, 'kiwix-lib'), pj(self.build_path, 'kiwixlib', 'src', 'main'))
  File "/home/kelson/kiwix-build/lib/python3.5/shutil.py", line 303, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kelson/kiwix-build/BUILD_android_arm/INSTALL/kiwix-lib'

```

**Comment by mgautierfr** [comment]
I don't know what happen here. 
Can you give me the logs file in `/home/kelson/kiwix-build/BUILD_android_arm/LOGS` ?

What is the version of kiwix-build you're using (`git describe --all --long`) ?

**Comment by kelson42** [comment]
I can not reproduce the problem but now I have a crash a bit later

```
$ ./build_custom_app.py --step publish --custom-app wikimed --google-api-key $GOOGLE_API_KEY --zim-path wikipedia_en_medicine_novid_2017-07.zim --apks-dir signed_apks --content-version-code $CONTENT_VERSION_CODE
Try to get package name from info.json file
Try to get zim url from info.json file
Try to get version_name form info.json file
Found package_name 'org.kiwix.kiwixcustomwikimed'
Found zim_url 'https://download.kiwix.org/zim/wikipedia_en_medicine.zim'
Found version_name '2016-09'
Traceback (most recent call last):
  File "./build_custom_app.py", line 430, in <module>
    func(options)
  File "./build_custom_app.py", line 152, in do_publish
    googleService = Google(options)
  File "./build_custom_app.py", line 346, in __init__
    scopes=[scope])
  File "/tmp/kiwix-build/lib/python3.5/site-packages/oauth2client/service_account.py", line 220, in from_json_keyfile_name
    client_credentials = json.load(file_obj)
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/tmp/kiwix-build/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
```

**Comment by mgautierfr** [comment]
What is your GOOGLE_API_KEY ? (It should be the json version)

**Comment by kelson42** [comment]
Yes, was the wrong format.
