### ISSUE TITLE
Cannot build kiwix-desktop for Windows

### ISSUE THREAD

**Issue by sgourdas** [kiwix/kiwix-build#758]
I have setup my environment for Windows building based on the [wiki guide](https://github.com/kiwix/kiwix-build/wiki/Setup-dev-environment-en-Windows).

When running `kiwix-build kiwix-desktop --config native_static` my build fails at the following:

```
...

[11/108] "cl" "-Itest\regex.exe.p" "-Iinclude" "-I..\..\SOURCE\libkiwix\include" "-I..\..\SOURCE\libkiwix\subprojects\googletest-release-1.8.1\googletest\include" "-Isubprojects\googletest-release-1.8.1\googletest" "-I..\..\SOURCE\libkiwix\subprojects\googletest-release-1.8.1\googletest" "-IC:/Users/jim31/WDIR/BUILD_native_static/INSTALL/include" "-IC:\Users\jim31\WDIR\BUILD_native_static\INSTALL\include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/W2" "/WX" "/EHsc" "/std:c++17" "/permissive-" "/Od" "/Zi" "-DNOMINMAX" "-DCURL_STATICLIB" "-DLZMA_API_STATIC" "-DSORTPP_PASS" "/Fdtest\regex.exe.p\.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.pdb" /Fotest/regex.exe.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.obj "/c" ../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/src/gtest-all.cc
[12/108] "cl" "-Itest\tagParsing.exe.p" "-Iinclude" "-I..\..\SOURCE\libkiwix\include" "-I..\..\SOURCE\libkiwix\subprojects\googletest-release-1.8.1\googletest\include" "-Isubprojects\googletest-release-1.8.1\googletest" "-I..\..\SOURCE\libkiwix\subprojects\googletest-release-1.8.1\googletest" "-IC:/Users/jim31/WDIR/BUILD_native_static/INSTALL/include" "-IC:\Users\jim31\WDIR\BUILD_native_static\INSTALL\include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/W2" "/WX" "/EHsc" "/std:c++17" "/permissive-" "/Od" "/Zi" "-DNOMINMAX" "-DCURL_STATICLIB" "-DLZMA_API_STATIC" "-DSORTPP_PASS" "/Fdtest\tagParsing.exe.p\.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.pdb" /Fotest/tagParsing.exe.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.obj "/c" ../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/src/gtest-all.cc
[13/108] "cl" "-Itest\stringTools.exe.p" "-Iinclude" "-I..\..\SOURCE\libkiwix\include" "-I..\..\SOURCE\libkiwix\subprojects\googletest-release-1.8.1\googletest\include" "-Isubprojects\googletest-release-1.8.1\googletest" "-I..\..\SOURCE\libkiwix\subprojects\googletest-release-1.8.1\googletest" "-IC:/Users/jim31/WDIR/BUILD_native_static/INSTALL/include" "-IC:\Users\jim31\WDIR\BUILD_native_static\INSTALL\include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/W2" "/WX" "/EHsc" "/std:c++17" "/permissive-" "/Od" "/Zi" "-DNOMINMAX" "-DCURL_STATICLIB" "-DLZMA_API_STATIC" "-DSORTPP_PASS" "/Fdtest\stringTools.exe.p\.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.pdb" /Fotest/stringTools.exe.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.obj "/c" ../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/src/gtest-all.cc
[14/108] "cl" "-Itest\library.exe.p" "-Iinclude" "-I..\..\SOURCE\libkiwix\include" "-I..\..\SOURCE\libkiwix\subprojects\googletest-release-1.8.1\googletest\include" "-Isubprojects\googletest-release-1.8.1\googletest" "-I..\..\SOURCE\libkiwix\subprojects\googletest-release-1.8.1\googletest" "-IC:/Users/jim31/WDIR/BUILD_native_static/INSTALL/include" "-IC:\Users\jim31\WDIR\BUILD_native_static\INSTALL\include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/Zc:__cplusplus" "/W2" "/WX" "/EHsc" "/std:c++17" "/permissive-" "/Od" "/Zi" "-DNOMINMAX" "-DCURL_STATICLIB" "-DLZMA_API_STATIC" "-DSORTPP_PASS" "/Fdtest\library.exe.p\.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.pdb" /Fotest/library.exe.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.obj "/c" ../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/src/gtest-all.cc
ninja: build stopped: subcommand failed.


Stopping build due to errors
```

Is there anything that indicates the issue? How should I proceed? I am not sure what I am doing wrong.

**Comment by kelson42** [comment]
"ninja" is installed?

**Comment by sgourdas** [comment]
> "ninja" is installed?

Yes it is. All tools needed on documentation are.

**Comment by kelson42** [comment]
@veloman-yunkan Would you be able please to help @sgourdas ?

**Comment by veloman-yunkan** [comment]
There is no error in the provided partial log. May it be that the error is in the omitted portion of the log?

**Comment by sgourdas** [comment]
Isn't kiwix-build supposed to build libkiwix? Should I build something else myself? I do not understand what is the issue.

**Comment by mgautierfr** [comment]
What is the content of `cmd_configure_kixiwi-desktop.log` in `BUILD_native_static/LOGS` directory ?

**Comment by sgourdas** [comment]
> What is the content of `cmd_configure_kixiwi-desktop.log` in `BUILD_native_static/LOGS` directory ?

```
...
Package kiwix was not found in the pkg-config search path.
Perhaps you should add the directory containing `kiwix.pc'
to the PKG_CONFIG_PATH environment variable
No package 'kiwix' found
Package kiwix was not found in the pkg-config search path.
Perhaps you should add the directory containing `kiwix.pc'
to the PKG_CONFIG_PATH environment variable
No package 'kiwix' found
Traceback (most recent call last):
  File "C:\Users\jim31\WDIR\SOURCE\kiwix-desktop\scripts\pkg-config-wrapper.py", line 58, in <module>
    pkg_output = forward_to_pkg_config()
  File "C:\Users\jim31\WDIR\SOURCE\kiwix-desktop\scripts\pkg-config-wrapper.py", line 29, in forward_to_pkg_config
    completeProcess = subprocess.run(
  File "C:\Users\jim31\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pkg-config', '--libs', '--static', 'kiwix >= 14.0.0 kiwix < 15.0.0 libzim >= 9.0.0 libzim < 10.0.0']' returned non-zero exit status 1.
Package kiwix was not found in the pkg-config search path.
Perhaps you should add the directory containing `kiwix.pc'
to the PKG_CONFIG_PATH environment variable
No package 'kiwix' found
Package kiwix was not found in the pkg-config search path.
Perhaps you should add the directory containing `kiwix.pc'
to the PKG_CONFIG_PATH environment variable
No package 'kiwix' found
Traceback (most recent call last):
  File "C:\Users\jim31\WDIR\SOURCE\kiwix-desktop\scripts\pkg-config-wrapper.py", line 58, in <module>
    pkg_output = forward_to_pkg_config()
  File "C:\Users\jim31\WDIR\SOURCE\kiwix-desktop\scripts\pkg-config-wrapper.py", line 29, in forward_to_pkg_config
    completeProcess = subprocess.run(
  File "C:\Users\jim31\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pkg-config', '--libs', '--static', 'kiwix >= 14.0.0 kiwix < 15.0.0 libzim >= 9.0.0 libzim < 10.0.0']' returned non-zero exit status 1.
Package kiwix was not found in the pkg-config search path.
Perhaps you should add the directory containing `kiwix.pc'
to the PKG_CONFIG_PATH environment variable
No package 'kiwix' found
Package kiwix was not found in the pkg-config search path.
Perhaps you should add the directory containing `kiwix.pc'
to the PKG_CONFIG_PATH environment variable
No package 'kiwix' found
Traceback (most recent call last):
  File "C:\Users\jim31\WDIR\SOURCE\kiwix-desktop\scripts\pkg-config-wrapper.py", line 58, in <module>
    pkg_output = forward_to_pkg_config()
  File "C:\Users\jim31\WDIR\SOURCE\kiwix-desktop\scripts\pkg-config-wrapper.py", line 29, in forward_to_pkg_config
    completeProcess = subprocess.run(
  File "C:\Users\jim31\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['pkg-config', '--libs', '--static', 'kiwix >= 14.0.0 kiwix < 15.0.0 libzim >= 9.0.0 libzim < 10.0.0']' returned non-zero exit status 1.
```

**Comment by veloman-yunkan** [comment]
That build failure is the result of kiwix/libkiwix#1133. Address it by applying kiwix/kiwix-desktop#1213 to your worktree.

**Comment by sgourdas** [comment]
> That build failure is the result of [kiwix/libkiwix#1133](https://github.com/kiwix/libkiwix/pull/1133). Address it by applying [kiwix/kiwix-desktop#1213](https://github.com/kiwix/kiwix-desktop/pull/1213) to your worktree.

Thanks a lot! This fixes it.
