### ISSUE TITLE
Bad archive base_deps_windows_native_static_09.tar.gz

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-build#770]
The archive at https://tmp.kiwix.org/ci/base_deps_windows_native_static_09.tar.gz seems to be corrupted.

```
$ tar tzf base_deps_windows_native_static_09.tar.gz 
SOURCE/icu4c-73.2/.extract_ok
SOURCE/pugixml-1.2/.extract_ok
...
... /* omitting some output */
....
BUILD_win-amd64/INSTALL/bin/icuuc74.dll
BUILD_win-amd64/INSTALL/bin/testplug.dll
BUILD_win-amd64/libcurl/.install_ok

gzip: stdin: decompression OK, trailing garbage ignored
BUILD_win-amd64/xapian-core-1.4.26/.test_ok
BUILD_win-amd64/zlib-1.2.12/.compile_ok
BUILD_win-amd64/docoptcpp-0.6.2/.install_ok
ARCHIVE/.download_boostregex_ok
ARCHIVE/.download_libcurl_ok
ARCHIVE/.download_docoptcpp-0.6.2_ok
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

There is no such problem with its [predecessor](https://tmp.kiwix.org/ci/base_deps_windows_native_static_08.tar.gz).

**Comment by kelson42** [comment]
Sounds like an upload problem, maybe we shozld just triiger a new version of these base deps?

**Comment by veloman-yunkan** [comment]
Can't we just delete the corrupted archive? Then it should be regenerated by the next `kiwix-build` CI run.

**Comment by rgaudin** [comment]
Deleted.

**Comment by veloman-yunkan** [comment]
The file was regenerated. It is 24 bytes larger than the previous corrupted one, however it seems to be incomplete too:

```
$ wget https://tmp.kiwix.org/ci/base_deps_windows_native_static_09.tar.gz
--2024-10-28 18:41:55--  https://tmp.kiwix.org/ci/base_deps_windows_native_static_09.tar.gz
Resolving tmp.kiwix.org (tmp.kiwix.org)... 135.181.224.247
Connecting to tmp.kiwix.org (tmp.kiwix.org)|135.181.224.247|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 94067379 (90M) [application/octet-stream]
Saving to: ‘base_deps_windows_native_static_09.tar.gz’

base_deps_windows_native_static_09.tar.gz 100%[=====================================================================================>]  89.71M  4.28MB/s    in 31s     

2024-10-28 18:42:26 (2.93 MB/s) - ‘base_deps_windows_native_static_09.tar.gz’ saved [94067379/94067379]


$ tar tzf base_deps_windows_native_static_09.tar.gz
BUILD_win-amd64/xapian-core-1.4.26/.configure_ok
BUILD_win-amd64/pugixml-1.2/.test_ok
...
... /* omitting some output */
....
SOURCE/zim-testing-suite-0.6.0/withns/wikibooks_be_all_nopic_2017-02_splitted.zimac
SOURCE/zim-testing-suite-0.6.0/withns/wikipedia_en_climate_change_nopic_2020-01.zim

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

```

**Comment by veloman-yunkan** [comment]
And it causes CI to fail. For example - https://github.com/kiwix/kiwix-build/actions/runs/11545702517/job/32132991525

```
Run python .github\\scripts\\ensure_base_deps.py
--- Getting archive base_deps_windows_native_static_09.tar.gz ---
D:\a\kiwix-build\kiwix-build\.github\scripts\ensure_base_deps.py:55: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  f.extractall(str(HOME))
Traceback (most recent call last):
  File "D:\a\kiwix-build\kiwix-build\.github\scripts\ensure_base_deps.py", line 72, in <module>
    main()
  File "D:\a\kiwix-build\kiwix-build\.github\scripts\ensure_base_deps.py", line 55, in main
    f.extractall(str(HOME))
  File "C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\tarfile.py", line 2302, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\tarfile.py", line 2365, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\tarfile.py", line 2448, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\tarfile.py", line 2502, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\tarfile.py", line 251, in copyfileobj
    buf = src.read(bufsize)
          ^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\gzip.py", line 324, in read
    return self._buffer.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\gzip.py", line 537, in read
    uncompress = self._decompressor.decompress(b"", size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: invalid stored block lengths
............
Error: Process completed with exit code 1.```

**Comment by veloman-yunkan** [comment]
This is the CI run that generated the archive - https://github.com/kiwix/kiwix-build/actions/runs/11490952502/job/31982506897

**Comment by kelson42** [comment]
@veloman-yunkan I guess we should just change the timing of the action workflow then.

**Comment by kelson42** [comment]
I reopen this issue because this keep hapening these last days. See for example https://tmp.kiwix.org/ci/deps_linux-x86_64-dyn_libzim.tar.gz which make the CI of libzim failing https://github.com/openzim/libzim/actions/runs/14397957552/job/40377132844?pr=967.

@rgaudin Can you please have a look, it's not even sure the problem is client side.

**Comment by kelson42** [comment]
@rgaudin Thx for the analysis, can we not queueing the upload operations? Or set a lock on the directory with flock or similar?

**Comment by rgaudin** [comment]
We can not queue uploads: the only thing linking those actions are the GH matrix which we can't do much about:

- we could disable concurrency but that's not what we want
- we could split this huge matrix into seperate ones but that would be harder to maintain

Locking, I suppose you meant on the target file, that's possible but a bit hackish.

One thing we could do is look for the file first, on the remote filesystem, at time of upload and stop if it exists. Currently, we go straight to writing. We did check via HTTP long-ago (at that time it wasn't there) and then decided to build (takes time) then upload.

Another thing we can do (in combination with it) is upload to a unique temp filename and move the file once upload is complete. It serves the same purpose as the lock but with two advantages:
- It prevents other jobs from picking up an incomplete file because it's available via HTTP
- With the lock, if it crashes before the lock is removed, the lock stays forever and one has to manually delete it. With the move strategy, if it fails and never gets moved to the final location, then another job will upload it.

Do you want a PR for that? Should be contained to that `upload()` function in `common.py`.

**Comment by kelson42** [comment]
@rgaudin Probably a silly question, but could we not avoid this problem by just securing thatonly focal uploads that file? This is not a general fix, but it seems silly that this is uploaded twice under the same name! We wamt either one or the other!

**Comment by rgaudin** [comment]
We could and that's easier obviously but it'd still be a bit hackish. We'd have to add an environ like `DONT_UPLOAD_DEPS` and add an `if` statement in the code before the upload.

I find it less elegant and as you mentioned, problem can surface elsewhere but it's up to you

**Comment by mgautierfr** [comment]
All of this is already piloted by build_definition.py

This commit https://github.com/kiwix/kiwix-build/commit/ff2ade262cb24e842b4a309e7592dd99fb2f771f
add two lines (focal and jammy) with both build definition and publish them (letter `d`) under the same name "linux-x86_64-dyn"

**Comment by kelson42** [comment]
After discussion with @rgaudin, thre measures will be taken:
* Will we try to get rid of Ubuntu 20.04 (active maintenance window is over and we have to move forward to provide qt6 for Kiwix De@ktop)
* We will recheck the deps file presence just before upload (and not only before building) AND we will upload on a temporary name and move at last moment (to reduce the race condition risk window)
* We will get rid of this "native" filenames, see #810

**Comment by mgautierfr** [comment]
The root problem is that two different archives are published under the same name. Not that the upload is done in the same time. Removing the `d` letter for libzim/libkiwix for the jammy builder should fix the issue.

**Comment by mgautierfr** [comment]
With `d` in the cell jammy/libzim, the CI build all dependencies of libzim (not libzim itself), package them and publish it as `deps_<archive_name>_libzim.tar.gz`

This archive is used by libzim's CI as cache to avoid recompile all dependencies there.
Only one job should build and publish it.

If you want to build libzim to check it can be build, use the letter `B`.
If you don't care and simply build kiwix-desktop, only fill the kiwix-desktop cell and keep the libzim cell empty. (Libzim will still be compiled as it is a dependency of kiwix-desktop and kiwix-build (the tool, not the CI) handle that)

**Comment by kelson42** [comment]
Closing this issue as all next steps are tracked in dedicated issues.
