### ISSUE TITLE
Problems building kiwix-desktop in release mode

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-build#777]
While working on kiwix/kiwix-build#757 I tried to build `kiwix-desktop` under Windows in release mode (`kiwix-build --make-release ...`) and ran against the problem with the `libcurl` dependency - its installation step fails because of a missing `strip` utility under Windows:

```
(venv) C:\Kiwix\builddir.release>kiwix-build --config native_static --make-release --skip-source-prepare --build-nodeps libcurl
... 
[0/1] "C:\Kiwix\venv\Scripts\meson" "install" "--no-rebuild"
Traceback (most recent call last):
  File "C:\Kiwix\venv\Lib\site-packages\mesonbuild\mesonmain.py", line 188, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Kiwix\venv\Lib\site-packages\mesonbuild\minstall.py", line 869, in run
    installer.do_install(datafilename)
  File "C:\Kiwix\venv\Lib\site-packages\mesonbuild\minstall.py", line 549, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "C:\Kiwix\venv\Lib\site-packages\mesonbuild\minstall.py", line 751, in install_targets
    self.do_strip(d.strip_bin, fname, outname)
  File "C:\Kiwix\venv\Lib\site-packages\mesonbuild\minstall.py", line 602, in do_strip
    returncode, stdo, stde = self.Popen_safe(strip_bin + [outname])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Kiwix\venv\Lib\site-packages\mesonbuild\minstall.py", line 359, in Popen_safe
    p, o, e = Popen_safe(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Kiwix\venv\Lib\site-packages\mesonbuild\utils\universal.py", line 1550, in Popen_safe
    p, o, e = Popen_safe_legacy(args, write=write, stdin=stdin, stdout=stdout, stderr=stderr, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Kiwix\venv\Lib\site-packages\mesonbuild\utils\universal.py", line 1572, in Popen_safe_legacy
    p = subprocess.Popen(args, universal_newlines=False, close_fds=False,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified
Installing lib\libcurl.a to C:\Kiwix\builddir.release\BUILD_native_static\INSTALL\lib
Installing src\curl.exe to C:\Kiwix\builddir.release\BUILD_native_static\INSTALL\bin
Stripping target 'src\\curl.exe'.

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.
FAILED: meson-internal__install
"C:\Kiwix\venv\Scripts\meson" "install" "--no-rebuild"
ninja: build stopped: subcommand failed.


Stopping build due to errors
```

This issue will likely prevent releasing kiwix-desktop v2.4

**Comment by kelson42** [comment]
@veloman-yunkan We had already a fix on Kiwix Desktop side https://github.com/kiwix/kiwix-desktop/issues/1059... so it seems this was not enough!
