### ISSUE TITLE
build custom apk - KeyError: 'VERSION_CODE'

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-build#80]
Continue from #79 with pip3 install pillow

./kiwix-build.py --verbose --target-platform android_arm --android-custom-app wikimedar kiwix-android-custom --zim-file-url https://download.kiwix.org/zim/wikipedia/wikipedia_ar_medicine_2017-08.zim

  download_zim kiwix-android-custom : Sha256 for wikipedia_ar_medicine_2017-08.zim not set, do no verify download
OK
  compile kiwix-android-custom : ERROR
Traceback (most recent call last):
  File "./kiwix-build.py", line 990, in <module>
    builder.run()
  File "./kiwix-build.py", line 928, in run
    self.build()
  File "./kiwix-build.py", line 918, in build
    builder.build()
  File "/opt/cesar-build/kiwix-build/dependencies.py", line 447, in build
    self.command('compile', self._compile)
  File "/opt/cesar-build/kiwix-build/dependency_utils.py", line 206, in command
    return self.target.command(*args, **kwargs)
  File "/opt/cesar-build/kiwix-build/dependency_utils.py", line 50, in command
    ret = function(*args, context=context)
  File "/opt/cesar-build/kiwix-build/dependency_utils.py", line 369, in _compile
    gradle_option=self.gradle_option)
  File "/opt/cesar-build/kiwix-build/dependencies.py", line 423, in gradle_option
    version_code=os.environ['VERSION_CODE'],
  File "/opt/cesar-build/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'VERSION_CODE'

**Comment by mgautierfr** [comment]
You must set the environment variable VERSION_CODE.
The VERSION_CODE to use is described here : https://github.com/kiwix/kiwix-build/wiki/Build-and-publish-a-custom-app-locally-(without-travis)#build-custom-app-apk
